project:
  type: book

lang: he
dir: rtl
book:
  title: "My Professional Book"
  cover-image: cover.svg
  author: "Your Name"
  chapters:
    - index.md
    - intro.md
    - mitzvot.md
    - sinaic_laws.md
    - orma.md
    - problem1_health.md
    - problem2_prat.md
    - problem3_animal.md
    - problem4_women.md
    - problem5_technology.md
    # - chapter4.qmd
    # - chapter5.qmd
    # - chapter6.qmd
    # - chapter7.qmd
    # - chapter8.qmd
    # - chapter9.qmd
    # - chapter10.qmd
    # - chapter11.qmd

format:
  html:
    theme: cosmo
  typst:
    papersize: a4
    section-numbering: 1.1.א
    columns: 1
    toc: true
    mainfont: "Assistant" # Or "David Libre", "Frank Ruhl Libre"
    fontsize: 11pt
  epub:
    toc: true
  docx:
    toc: true